### ISSUE TITLE
Messages are glitched.

### ISSUE THREAD

**Issue by yonderbread** [ct-js/ct-js-installer#13]
![Screenshot_1](https://user-images.githubusercontent.com/33736622/91495038-be00ee00-e86e-11ea-955e-b497c9d065cc.png)

**Comment by CosmoMyzrailGorynych** [comment]
Seems to be a Windows' issue, can't replicate on Linux:

![изображение](https://user-images.githubusercontent.com/3174357/91496810-e93c1980-e910-11ea-9ebb-e4fc7b1b9bfa.png)

The issue is probably because I used ellipsis instead of three periods. Let's change it and see what happens.

I must also note that Splushy's header looks pixelated when they clearly have font antialiasing enabled on their system

**Comment by CosmoMyzrailGorynych** [comment]
@yonderbread Could you try this branch? https://github.com/ct-js/ct-js-installer/tree/fix-13

**Comment by yonderbread** [comment]
> @yonderbread Could you try this branch? https://github.com/ct-js/ct-js-installer/tree/fix-13

Yep, will try that.

**Comment by yonderbread** [comment]
@CosmoMyzrailGorynych 
![Screenshot_2](https://user-images.githubusercontent.com/33736622/91500421-5d76ae80-e878-11ea-9763-2882d3f7d8cc.png)
![Screenshot_1](https://user-images.githubusercontent.com/33736622/91500427-5e0f4500-e878-11ea-9af0-0bbf207905e7.png)

It seems that there some other issues, although I wasn't seeing the glitch anymore.

**Comment by CosmoMyzrailGorynych** [comment]
Well, yes, it couldn't fit :/ So there is a continuation of this issue with the wrong font. Will look into it later, currently at work, and don't have access to Windows PC.

**Comment by yonderbread** [comment]
@CosmoMyzrailGorynych I'll try to implement auto-sizing fonts for different lengths of text

**Comment by yonderbread** [comment]
Something you may want to check out is QSizePolicy for QLabel
```QLabel.setSizePolicity(QSizePolicy.EXPANDING, QSizePolicy.EXPANDING)```
https://doc.qt.io/qtforpython/PySide2/QtWidgets/QSizePolicy.html

**Comment by naturecodevoid** [comment]
Just fixed it, I replaced the special `...` with normal dots.
